[web_servers]
web-1 ansible_host="34.79.15.105"
web-2 ansible_host="34.78.143.141"
web-3 ansible_host="34.77.52.107"
web-4 ansible_host="35.205.78.186"
web-5 ansible_host="35.190.202.3"
[web_servers:vars]
ansible_user=ogarcia
ansible_ssh_private_key_file=../tf/terraform-key
